export const GET_DOGS= "GET_DOGS"
export const GET_BY_NAME= "GET_BY_NAME"
export const GET_DETAIL= "GET_DETAIL"
export const CLEAR_DETAIL= "CLEAR_DETAIL"
export const GET_TEMPERAMENT="GET_TEMPERAMENT"

export const POST_DOG="POST_DOG"

export const ORDER_BY_NAME="ORDER_BY_NAME"
export const ORDER_WEIGHT="ORDER_WEIGHT"

export const FILTER_CREATED = "FILTER_CREATED"
export const FILTER_BY_TEMPERAMENT="FILTER_BY_TEMPERAMENT"